### ISSUE TITLE
Missing SQL to Create DB and Tables

### ISSUE THREAD

**Issue by javierisaai** [RizkiMufrizal/Spring-OAuth2-Custom#1]
Your project is very interesting, however you are missing the files to create the database objects. Can you please provide them?

You would typically place the SQL dependencies under:
/src/main/resources/sql

Thanks in advance!

**Comment by RizkiMufrizal** [comment]
hy javierisaai,
in this project, i use hibernate framework for create the database tables, and i not yet use [flywaydb](https://flywaydb.org/) for database migration. In future, i will create a database migration for this project.

**Comment by RizkiMufrizal** [comment]
now i use flywaydb for database migration, check out https://github.com/RizkiMufrizal/Spring-OAuth2-Custom/blob/master/src/main/resources/db/migration/V0.0.1.20170207__Skema%20Awal.sql

**Comment by javierisaai** [comment]
Great! I am closing this now. Will let you know if I have more feedback.
Keep up the good work!
